"""Automatic migration

Revision ID: 51994b7214af
Revises: bf996b126a27
Create Date: 2020-09-07 11:48:01.866837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51994b7214af'
down_revision = 'bf996b126a27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dot_collisions', sa.Column('snapshot', sa.Text(4294000000), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dot_collisions', 'snapshot')
    # ### end Alembic commands ###
