"""Automatic migration

Revision ID: 69f22227b8a1
Revises: 4a3eecadfb68
Create Date: 2020-08-31 20:47:08.891596

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '69f22227b8a1'
down_revision = '4a3eecadfb68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dot_state_collision_time', table_name='dot_state')
    op.drop_table('dot_state')
    op.add_column('dot', sa.Column('dot_name', sa.String(length=128), nullable=False))
    op.add_column('dot', sa.Column('speed', sa.Float(), nullable=False))
    op.add_column('dot', sa.Column('started_at', sa.BigInteger(), nullable=False))
    op.add_column('dot', sa.Column('status', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dot', 'status')
    op.drop_column('dot', 'started_at')
    op.drop_column('dot', 'speed')
    op.drop_column('dot', 'dot_name')
    op.create_table('dot_state',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('collided_with', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('collision_time', mysql.DATETIME(), nullable=True),
    sa.Column('state', mysql.TEXT(), nullable=False),
    sa.Column('dot_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['dot_id'], ['dot.id'], name='dot_state_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_dot_state_collision_time', 'dot_state', ['collision_time'], unique=False)
    # ### end Alembic commands ###
