"""Automatic migration

Revision ID: 80205987c8cc
Revises: 69f22227b8a1
Create Date: 2020-09-01 14:21:36.355543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80205987c8cc'
down_revision = '69f22227b8a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dot_files', sa.Column('file_hash', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dot_files', 'file_hash')
    # ### end Alembic commands ###
