"""Automatic migration

Revision ID: b8b568d06de5
Revises: 9ea9b7124756
Create Date: 2020-08-27 20:05:46.747301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8b568d06de5'
down_revision = '9ea9b7124756'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dot_files', sa.Column('content', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dot_files', 'content')
    # ### end Alembic commands ###
