"""Automatic migration

Revision ID: bf996b126a27
Revises: 80205987c8cc
Create Date: 2020-09-04 12:28:25.856197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf996b126a27'
down_revision = '80205987c8cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dot', sa.Column('script', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dot', 'script')
    # ### end Alembic commands ###
